{% set name = "h5utils" %}
{% set version = "1.13.1" %}
{% set sha256 = "c5a76f064d6daa3e65583dce2b61202510e67cf6590f076af9a8aa72511d7d65" %}
{% set build = 1008 %}

# recipe-lint fails if mpi is undefined
{% set mpi = mpi or 'nompi' %}
{% if mpi == "nompi" %}
# prioritize nompi via build number
{% set build = build + 100 %}
{% endif %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/NanoComp/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  skip: true  # [win]
  {% if mpi != "nompi" %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  # add build string so packages can depend on
  # mpi or nompi variants
  # dependencies:
  # `h5utils * mpi_mpich_*` for mpich
  # `h5utils * mpi_*` for any mpi
  # `h5utils * nompi_*` for no mpi
  string: "{{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}"
  run_exports:
    - {{ name }} * {{ mpi_prefix }}_*

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - {{ mpi }}  # [mpi != 'nompi']
    - libpng
    # We need to list hdf5 twice to get version pinning from
    # conda_build_config.yaml, (which falls back to the one from conda-forge,)
    # and build pinning from {{ mpi_prefix }}
    - hdf5
    - hdf5 * {{ mpi_prefix }}_*
    - zlib
    - numpy
  run:
    - {{ mpi }}  # [mpi != 'nompi']
    - libpng
    - hdf5
    - zlib
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - h5py
    - numpy
  commands:
    - h5topng -h
    - h5totxt -h
    - h5fromtxt -h
    - h5tovtk -h

about:
  home: http:/github.com/NanoComp/h5utils
  license: MIT
  license_file: COPYING
  summary: A set of utilities for visualization and conversion of scientific data in the free portable HDF5 format
  doc_url: https://github.com/NanoComp/h5utils/tree/master/doc
  dev_url: https://github.com/NanoComp/h5utils

extra:
  recipe-maintainers:
    - ChristopherHogan
    - oskooi
    - RobinD42
